### ISSUE TITLE
Minify code? 

### ISSUE THREAD

**Issue by sfranzyshen** [cesanta/elk#16]
Does elk accept minified code?

does elk need spaces etc. to be able to parse? also how does elk handle the original source after parsing it? I understand elk doesn't perform a bytecode step so how is everything handled in ram?

**Comment by cpq** [comment]
Yes, it accepts minified code, provided it is in a valid JS syntax. The original source could be freed, elk does not reference it. Strings and functions get copied into elk's memory - so minification is good.
Functions are handled like callable strings, basically.
