### ISSUE TITLE
limited (seven) number of assignments in 'let' statements

### ISSUE THREAD

**Issue by sfranzyshen** [cesanta/elk#21]
there is a limit (7 from my testing) of assignments allowed in a 'let ' statement. easy fix is to limit the number assignments per let ... but some minimizes will group everything into one 'let ' ... is this a limit or a bug?

**Not Working**
`let a = 0, b = 0, c = 0, d = 5500, e = 45, f = 0, g = 0, h = 0, i = num();`

**Working**
`let a = 0, b = 0; let c = 5500, d = 0, e = 45, f = 0, g = 0, h = 0, i = num();`

btw: num() would have been defined elsewhere in the code ...

**Comment by cpq** [comment]
This is actually by design: elk uses a temporary stack for storing current operation and to omit recursion. Stack size is currently defined to 10. Maybe it makes sense to make it larger, but the limitation will stay anyway.
elk should throw an error on overflow.
