### ISSUE TITLE
Question: redefining in elk

### ISSUE THREAD

**Issue by sfranzyshen** [cesanta/elk#23]
I know that redefining variables and functions has been done in other JS environments ... but I'm not sure if it's actually proper javascript ... in testing it out with Elk ... I have experienced success and failure and i'd like to ask if first it's proper javascript ... and second if so ... will elk also support it? from my testing it seams to work as long as the string is shorter (number of characters) than the previous length defined (for variables, function, objects) and it seams to work fine with numbers ... also this too seams to work ... but not sure if it's good practice :)

```
let bee = function(x,s) {x*s};
function(x,s) {x*s}
bee
function(x,s) {x*s}
bee(1,2);
2
let tree = function() {};
function() {}
bee(1,2);
2
tree = bee;
function(x,s) {x*s}
tree
function(x,s) {x*s}
tree(1,2);
2
```

**Comment by cpq** [comment]
That should work.
