### ISSUE TITLE
Question: Elk's GPLv2 license and binary firmware distribution?

### ISSUE THREAD

**Issue by sfranzyshen** [cesanta/elk#24]
I am planning on releasing a project that depends on the Elk Library and would like to have a (precompiled) binary firmware version available ... are there any restrictions under Elk's GPLv2 license to prevent distributing a project in a binary form? There would be acknowledgement for the origin of the code used, and the project source code would also be open sourced.

**Comment by cpq** [comment]
Not a lawyer - as to my knowledge, if the project is open source, it is fine.
