### ISSUE TITLE
Compile on ubuntu linux fails ...

### ISSUE THREAD

**Issue by sfranzyshen** [cesanta/elk#32]
I am not able to build on ubuntu linux with the following error;
```
/usr/bin/ld: /tmp/ccjf3pKm.o: undefined reference to symbol 'pow@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:45: recipe for target 'cli' failed
make: *** [cli] Error 1
```
I added '-lm' to the CFLAGS in the Makefile to fix the problem ...
`CFLAGS ?= -lm -W -Wall -Werror -Wno-deprecated -I.. -g -fsanitize=address,undefined -coverage $(EXTRA)
`
I am not sure how this will affect other platforms ...

**Comment by cpq** [comment]
IMO the unit test build on ubuntu, so it works for sure.

That sort of issues are usually due to the order of linker flags, which unfortunately matters.
Try to set `-lm` as the last option.
